### ISSUE TITLE
Implement resetting the level upon the player character's death.

### ISSUE THREAD

**Issue by jkim-y** [Jkim-Hack/cse3902#147]

**Comment by alexbook45** [comment]
If it works for you, I can just call some game reset method in playercollidable whenever links health hits 0. So you would just need to worry about a method that can trigger a reset

**Comment by PranavKoduri** [comment]
There will be 2 types of resets - reset when Link leaves a room and when Link dies or is grabbed my wall master. Link leaving the room is already implemented (roomHandler.Reset()), but the other reset isn't done yet.
