### ISSUE TITLE
Wallmaster movement/behavior fix

### ISSUE THREAD

**Issue by alexbook45** [Jkim-Hack/cse3902#215]
Wallmasters need to chase after link when he gets near them. Additionally, they have a different general movement pattern than they currently do in our game.

**Comment by PranavKoduri** [comment]
Once this is fixed, in PlayerCollidable.cs, this needs to be uncommented:

![image](https://user-images.githubusercontent.com/61212259/113421027-5ed10200-9398-11eb-8d54-3a0987135dc5.png)

this may actually be better to do with #233 instead
